---
  - hosts: all
    become_user: root
    become: yes
    
    vars:
      pip_install_packages:
        - name: opera
      pip_package: python3-pip
      pip_executable: pip3  
  
    pre_tasks:
    - name: update cache
      package:
        update_cache: yes  
  
    roles:
      - role: geerlingguy.pip

    tasks:  
      - name: add blueprint files to host
        become: yes
        become_user: ubuntu
        block:
        - file: path="/home/ubuntu/opera/sodalite-uc/" state=directory       
        - synchronize:
            src: "{{ blueprint_path }}"
            dest: "/home/ubuntu/opera/sodalite-uc/"   

      - name: install roles
        become: yes
        become_user: ubuntu
        command: ansible-galaxy install -r /home/ubuntu/opera/sodalite-uc/requirements.yml 
